### ISSUE TITLE
Anyone else getting 'too many 500 error responses'

### ISSUE THREAD

**Issue by random25252** [lazeroffmichael/ticktick-py#42]
Wondering if anybody else is getting a similar error:
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ticktick.com', port=443): Max retries exceeded with url: /api/v2/user/signin?wc=True&remember=True (Caused by ResponseError('too many 500 error responses'))

I had this over a year ago and it was some server side anti-fraud measure that eventually went away. But I've left it for days this time and it doesn't seem to be going away. If people are also experiencing this I can provide more troubleshooting I've done otherwise if there are still people using this successfully please let me know and it's surely an issue just on my end somehow.

Cheers!

**Comment by random25252** [comment]
Hey @btw04 sorry to ping you here but you're the last person I can see active using this. I wonder if you're still using it succesfully with the unofficial API endpoints or maybe they have blocked access?

**Comment by btw04** [comment]
Hi!
After a bit of testing it turned out that the API endpoint now _requires_ additional device-data. 
I have no idea why this is the case (maybe this messed with their data or something?) but the only necessary adjustment was to add a header that tells ticktick.com which device you are using... You can check out my fix [https://github.com/btw04/ticktick-py/commit/573d1a77ec4558738829ae0ee191460705c58386](here). 
I'm not quite sure what the requirments for the id are right now, the first few digits have to be what they are right now, otherwise it doesn't work. That is also the reason why I haven't created a pull-request yet, as I want to check if this id is somehow timebased

**Comment by nathanmargaglio** [comment]
Same here.  @btw04's fix appears to work (so far).

I also wanted to add that I'm seeing some issues with the app on my Android phone.  It doesn't appear to be syncing with the online app, and I'm getting some errors indicating that it's failing to communicate with the server.  So it's possible that they changed something in their server and it's also affecting the Android app.

**Comment by random25252** [comment]
Thank you @btw04 fix appears to work so far, for me too! Thank you for your work on this package for those of us less acquainted with APIs. 

For anyone interested, I found it easiest to implement this with
`USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:95.0) Gecko/20100101 Firefox/95.0"
X_DEVICE_ = '{"platform":"web","os":"OS X","device":"Firefox 95.0","name":"unofficial api!","version":4531,' \
                '"id":"6490' + secrets.token_hex(10) + '","channel":"website","campaign":"","websocket":""}'

TickTickClient.HEADERS = {'User-Agent': USER_AGENT,
               'x-device': X_DEVICE_}`

After:

`from ticktick.oauth2 import OAuth2  # OAuth2 Manager
from ticktick.api import TickTickClient  # Main Interface`

But before initialising the client, so that I could deploy my script without having to directly edit the installed package, but I'm not a python expert so please disregard if this is a poor way to perform this. 

Closing issue accordingly.
